### ISSUE TITLE
Check doesn't return current value

### ISSUE THREAD

**Issue by packetmonkey** [mdb/concourse-consul-kv-resource#1]
Hi! Thanks for making this concourse resource, it has made interacting with our consul servers in our CI pipelines very easy to work with!

I am however, unable to use the resource to trigger jobs if a consul value changes, instead it appears the `checkAction` [returns the current date](https://github.com/mdb/concourse-consul-kv-resource/blob/master/assets/lib/check.js#L16) instead of the value of the key which causes concourse to trigger the job in step with the polling of the key, as opposed to when the key has changed.

Would you accept a patch that changed the `ref: Date.now().toString()` to `value: value.value` in order to get this behavior?  By always returning the current version, it would appear to work with the guidance in the [concourse docs](http://concourse.ci/implementing-resources.html) around the example of a git resource having been `push -f`'ed over.

Thanks again for the resource!

**Comment by mdb** [comment]
@packetmonkey Good catch! If I understand correctly, the `value: value.value` behavior you're describing  sounds reasonable.
