### ISSUE TITLE
This resource displays the consul value on the pipeline. Consul value contains secret variables and it needs to be hidden. 

### ISSUE THREAD

**Issue by lakshminarjala-ops** [mdb/concourse-consul-kv-resource#12]
[
![Screenshot 2020-11-18 at 11 26 03 AM](https://user-images.githubusercontent.com/74649479/99505883-64105000-29a7-11eb-8ab8-1597e39b9da0.png)
](url)

**Comment by mdb** [comment]
Hi @lakshminarjala-ops - thanks for using the resource & for filing an issue. However, I'm a bit confused. 

1. To ensure I understand the behavior you're describing, could you please provide a detailed, step-by-step explanation of how to reproduce what you're observing using a local `docker-compose`'d setup similar to the one in the [README](https://github.com/mdb/concourse-consul-kv-resource#functional-testing)?
2. Are you suggesting that `concourse-consul-kv-resource` prints the values of the Consul k/v pairs it tracks? If so, that is expected, no? If the k/v pairs are secrets, I would think they should be stored in a proper secrets manager, such as [Vault](https://www.vaultproject.io/) and not fetched directly via the `concourse-consul-kv-resource`. Or am I misinterpreting?

**Comment by mdb** [comment]
I'm going to close this issue. @lakshminarjala-ops - please let me know if you continue to believe this is a valid issue.
