### ISSUE TITLE
feature request: support specifying the ca-cert file

### ISSUE THREAD

**Issue by eedwards-sk** [mdb/concourse-consul-kv-resource#3]
this is a feature request to support specifying the ca-cert file

i'm using root/intermediate/leaf pki pattern for my consul nodes, so I need to be able to specify the ca-cert file in addition to the consul client key/cert

**Comment by mdb** [comment]
@eedwards-sk Thanks for pointing this out and apologies it's taken so long to address it. `latest` and version `0.9.0` now support the ability to declare a `source.ca`. I'm going to close this issue for now but please don't hesitate to comment if you discover any issues. Thanks!
